---

  - name: Configure the OpenShift Access Control Layer
    hosts: itix
    become: yes
    tasks:
    - name: Nicolas is admin
      command: oc adm policy add-cluster-role-to-user cluster-admin nicolas.masse@itix.fr
